# Generated by Django 2.1.2 on 2018-10-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authorization_presentment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(max_length=15)),
                ('transaction_id', models.CharField(max_length=15)),
                ('merchant_name', models.CharField(max_length=15)),
                ('merchant_city', models.CharField(max_length=15)),
                ('merchant_country', models.CharField(max_length=15)),
                ('merchant_mcc', models.CharField(max_length=15)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_currency', models.CharField(max_length=3)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('settlement_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('settlement_currency', models.CharField(max_length=3)),
            ],
        ),
    ]
